# DO NOT MODIFY THIS FILE
# Generated by Bundler 0.9.25

require 'digest/sha1'
require 'yaml'
require 'pathname'
require 'rubygems'
Gem.source_index # ensure Rubygems is fully loaded in Ruby 1.9

module Gem
  class Dependency
    if !instance_methods.map { |m| m.to_s }.include?("requirement")
      def requirement
        version_requirements
      end
    end
  end
end

module Bundler
  class Specification < Gem::Specification
    attr_accessor :relative_loaded_from

    def self.from_gemspec(gemspec)
      spec = allocate
      gemspec.instance_variables.each do |ivar|
        spec.instance_variable_set(ivar, gemspec.instance_variable_get(ivar))
      end
      spec
    end

    def loaded_from
      return super unless relative_loaded_from
      source.path.join(relative_loaded_from).to_s
    end

    def full_gem_path
      Pathname.new(loaded_from).dirname.expand_path.to_s
    end
  end

  module SharedHelpers
    attr_accessor :gem_loaded

    def default_gemfile
      gemfile = find_gemfile
      gemfile or raise GemfileNotFound, "Could not locate Gemfile"
      Pathname.new(gemfile)
    end

    def in_bundle?
      find_gemfile
    end

    def env_file
      default_gemfile.dirname.join(".bundle/environment.rb")
    end

  private

    def find_gemfile
      return ENV['BUNDLE_GEMFILE'] if ENV['BUNDLE_GEMFILE']

      previous = nil
      current  = File.expand_path(Dir.pwd)

      until !File.directory?(current) || current == previous
        filename = File.join(current, 'Gemfile')
        return filename if File.file?(filename)
        current, previous = File.expand_path("..", current), current
      end
    end

    def clean_load_path
      # handle 1.9 where system gems are always on the load path
      if defined?(::Gem)
        me = File.expand_path("../../", __FILE__)
        $LOAD_PATH.reject! do |p|
          next if File.expand_path(p).include?(me)
          p != File.dirname(__FILE__) &&
            Gem.path.any? { |gp| p.include?(gp) }
        end
        $LOAD_PATH.uniq!
      end
    end

    def reverse_rubygems_kernel_mixin
      # Disable rubygems' gem activation system
      ::Kernel.class_eval do
        if private_method_defined?(:gem_original_require)
          alias rubygems_require require
          alias require gem_original_require
        end

        undef gem
      end
    end

    def cripple_rubygems(specs)
      reverse_rubygems_kernel_mixin

      executables = specs.map { |s| s.executables }.flatten
      Gem.source_index # ensure RubyGems is fully loaded

     ::Kernel.class_eval do
        private
        def gem(*) ; end
      end

      ::Kernel.send(:define_method, :gem) do |dep, *reqs|
        if executables.include? File.basename(caller.first.split(':').first)
          return
        end
        opts = reqs.last.is_a?(Hash) ? reqs.pop : {}

        unless dep.respond_to?(:name) && dep.respond_to?(:requirement)
          dep = Gem::Dependency.new(dep, reqs)
        end

        spec = specs.find  { |s| s.name == dep.name }

        if spec.nil?
          e = Gem::LoadError.new "#{dep.name} is not part of the bundle. Add it to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        elsif dep !~ spec
          e = Gem::LoadError.new "can't activate #{dep}, already activated #{spec.full_name}. " \
                                 "Make sure all dependencies are added to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        end

        true
      end

      # === Following hacks are to improve on the generated bin wrappers ===

      # Yeah, talk about a hack
      source_index_class = (class << Gem::SourceIndex ; self ; end)
      source_index_class.send(:define_method, :from_gems_in) do |*args|
        source_index = Gem::SourceIndex.new
        source_index.spec_dirs = *args
        source_index.add_specs(*specs)
        source_index
      end

      # OMG more hacks
      gem_class = (class << Gem ; self ; end)
      gem_class.send(:define_method, :bin_path) do |name, *args|
        exec_name, *reqs = args

        spec = nil

        if exec_name
          spec = specs.find { |s| s.executables.include?(exec_name) }
          spec or raise Gem::Exception, "can't find executable #{exec_name}"
        else
          spec = specs.find  { |s| s.name == name }
          exec_name = spec.default_executable or raise Gem::Exception, "no default executable for #{spec.full_name}"
        end

        gem_bin = File.join(spec.full_gem_path, spec.bindir, exec_name)
        gem_from_path_bin = File.join(File.dirname(spec.loaded_from), spec.bindir, exec_name)
        File.exist?(gem_bin) ? gem_bin : gem_from_path_bin
      end
    end

    extend self
  end
end

module Bundler
  ENV_LOADED   = true
  LOCKED_BY    = '0.9.25'
  FINGERPRINT  = "4d9ddb640901118f3c367fadf496f2f78489ac91"
  HOME         = '/Users/Remy/.bundle/ruby/1.8/bundler'
  AUTOREQUIRES = {:test=>[["bson_ext", false], ["email_spec", false], ["factory_girl", false], ["launchy", false], ["rspec", false], ["rspec-rails", false], ["remarkable_rails", false], ["rspactor", false], ["spork", false], ["webrat", false]], :default=>[["action_pack", true], ["comma", false], ["devise", false], ["devise_invitable", false], ["erubis", false], ["fastercsv", false], ["formtastic", false], ["haml", false], ["liquid", false], ["mongo_ext", false], ["mongo_mapper", false], ["rails", false], ["ssl_requirement", false], ["state_machine", false], ["will_paginate", false]], :development=>[["capistrano", false], ["ffaker", false]]}
  SPECS        = [
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/rake-0.8.7.gemspec", :name=>"rake", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/rake-0.8.7/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/abstract-1.0.0.gemspec", :name=>"abstract", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/abstract-1.0.0/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/activesupport-2.3.8.gemspec", :name=>"activesupport", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/activesupport-2.3.8/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/rack-1.1.0.gemspec", :name=>"rack", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/actionpack-2.3.8.gemspec", :name=>"actionpack", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/actionpack-2.3.8/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/actionmailer-2.3.8.gemspec", :name=>"actionmailer", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/actionmailer-2.3.8/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/activerecord-2.3.8.gemspec", :name=>"activerecord", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/activerecord-2.3.8/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/activeresource-2.3.8.gemspec", :name=>"activeresource", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/activeresource-2.3.8/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/bson-1.0.gemspec", :name=>"bson", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/bson-1.0/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/bson_ext-1.0.1.gemspec", :name=>"bson_ext", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/bson_ext-1.0.1/ext"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/highline-1.5.2.gemspec", :name=>"highline", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/highline-1.5.2/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/net-ssh-2.0.22.gemspec", :name=>"net-ssh", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/net-ssh-2.0.22/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/net-scp-1.0.2.gemspec", :name=>"net-scp", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/net-scp-1.0.2/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/net-sftp-2.0.4.gemspec", :name=>"net-sftp", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/net-sftp-2.0.4/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/net-ssh-gateway-1.0.1.gemspec", :name=>"net-ssh-gateway", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/net-ssh-gateway-1.0.1/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/capistrano-2.5.18.gemspec", :name=>"capistrano", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/capistrano-2.5.18/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/comma-0.3.2.gemspec", :name=>"comma", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/comma-0.3.2/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/configuration-1.1.0.gemspec", :name=>"configuration", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/configuration-1.1.0/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/warden-0.10.7.gemspec", :name=>"warden", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/warden-0.10.7/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/devise-1.0.7.gemspec", :name=>"devise", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/devise-1.0.7/lib"]},
        {:loaded_from=>"/Users/Remy/.bundle/ruby/1.8/bundler/gems/devise_invitable-e928539f5ce9c3ea1dae42e06af80fc85c8f6ade-cde70b0459c6e69fa9077605416705fe478074f5/devise_invitable.gemspec", :name=>"devise_invitable", :load_paths=>["/Users/Remy/.bundle/ruby/1.8/bundler/gems/devise_invitable-e928539f5ce9c3ea1dae42e06af80fc85c8f6ade-cde70b0459c6e69fa9077605416705fe478074f5/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/email_spec-0.6.2.gemspec", :name=>"email_spec", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/email_spec-0.6.2/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/erubis-2.6.5.gemspec", :name=>"erubis", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/erubis-2.6.5/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/factory_girl-1.2.4.gemspec", :name=>"factory_girl", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/factory_girl-1.2.4/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/fastercsv-1.5.3.gemspec", :name=>"fastercsv", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/fastercsv-1.5.3/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/ffaker-0.4.0.gemspec", :name=>"ffaker", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/ffaker-0.4.0/lib"]},
        {:loaded_from=>"/Users/Remy/.bundle/ruby/1.8/bundler/gems/formtastic-8ab93b34c3a97eee21e38185e14bed2f769c81e5-4b3bb6021b2ada5c18281bc7168e130a6901bca7/formtastic.gemspec", :name=>"formtastic", :load_paths=>["/Users/Remy/.bundle/ruby/1.8/bundler/gems/formtastic-8ab93b34c3a97eee21e38185e14bed2f769c81e5-4b3bb6021b2ada5c18281bc7168e130a6901bca7/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/haml-3.0.7.gemspec", :name=>"haml", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/haml-3.0.7/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/jnunemaker-validatable-1.8.4.gemspec", :name=>"jnunemaker-validatable", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/jnunemaker-validatable-1.8.4/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/launchy-0.3.5.gemspec", :name=>"launchy", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/launchy-0.3.5/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/liquid-2.0.0.gemspec", :name=>"liquid", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/liquid-2.0.0/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/mongo-1.0.gemspec", :name=>"mongo", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/mongo-1.0/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/mongo_ext-0.19.3.gemspec", :name=>"mongo_ext", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/mongo_ext-0.19.3/ext"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/plucky-0.1.1.gemspec", :name=>"plucky", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/plucky-0.1.1/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/mongo_mapper-0.7.6.gemspec", :name=>"mongo_mapper", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/mongo_mapper-0.7.6/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/nokogiri-1.4.2.gemspec", :name=>"nokogiri", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/nokogiri-1.4.2/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/rack-test-0.5.4.gemspec", :name=>"rack-test", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/rack-test-0.5.4/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/rails-2.3.8.gemspec", :name=>"rails", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/rails-2.3.8/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/rspec-1.3.0.gemspec", :name=>"rspec", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/rspec-1.3.0/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/remarkable-3.1.13.gemspec", :name=>"remarkable", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/remarkable-3.1.13/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/remarkable_activerecord-3.1.13.gemspec", :name=>"remarkable_activerecord", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/remarkable_activerecord-3.1.13/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/rspec-rails-1.3.2.gemspec", :name=>"rspec-rails", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/rspec-rails-1.3.2/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/remarkable_rails-3.1.13.gemspec", :name=>"remarkable_rails", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/remarkable_rails-3.1.13/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/rspactor-0.6.3.gemspec", :name=>"rspactor", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/rspactor-0.6.3/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/spork-0.8.3.gemspec", :name=>"spork", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/spork-0.8.3/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/ssl_requirement-0.1.0.gemspec", :name=>"ssl_requirement", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/ssl_requirement-0.1.0/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/state_machine-0.9.2.gemspec", :name=>"state_machine", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/state_machine-0.9.2/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/webrat-0.7.1.gemspec", :name=>"webrat", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/webrat-0.7.1/lib"]},
        {:loaded_from=>"/Users/Remy/.rvm/gems/ruby-1.8.7-p249/specifications/will_paginate-2.3.14.gemspec", :name=>"will_paginate", :load_paths=>["/Users/Remy/.rvm/gems/ruby-1.8.7-p249/gems/will_paginate-2.3.14/lib"]},
      ].map do |hash|
    if hash[:virtual_spec]
      spec = eval(hash[:virtual_spec], TOPLEVEL_BINDING, "<virtual spec for '#{hash[:name]}'>")
    else
      dir = File.dirname(hash[:loaded_from])
      spec = Dir.chdir(dir){ eval(File.read(hash[:loaded_from]), TOPLEVEL_BINDING, hash[:loaded_from]) }
    end
    spec.loaded_from = hash[:loaded_from]
    spec.require_paths = hash[:load_paths]
    if spec.loaded_from.include?(HOME)
      Bundler::Specification.from_gemspec(spec)
    else
      spec
    end
  end

  extend SharedHelpers

  def self.configure_gem_path_and_home(specs)
    # Fix paths, so that Gem.source_index and such will work
    paths = specs.map{|s| s.installation_path }
    paths.flatten!; paths.compact!; paths.uniq!; paths.reject!{|p| p.empty? }
    ENV['GEM_PATH'] = paths.join(File::PATH_SEPARATOR)
    ENV['GEM_HOME'] = paths.first
    Gem.clear_paths
  end

  def self.match_fingerprint
    lockfile = File.expand_path('../../Gemfile.lock', __FILE__)
    lock_print = YAML.load(File.read(lockfile))["hash"] if File.exist?(lockfile)
    gem_print = Digest::SHA1.hexdigest(File.read(File.expand_path('../../Gemfile', __FILE__)))

    unless gem_print == lock_print
      abort 'Gemfile changed since you last locked. Please run `bundle lock` to relock.'
    end

    unless gem_print == FINGERPRINT
      abort 'Your bundled environment is out of date. Run `bundle install` to regenerate it.'
    end
  end

  def self.setup(*groups)
    match_fingerprint
    clean_load_path
    cripple_rubygems(SPECS)
    configure_gem_path_and_home(SPECS)
    SPECS.each do |spec|
      Gem.loaded_specs[spec.name] = spec
      spec.require_paths.each do |path|
        $LOAD_PATH.unshift(path) unless $LOAD_PATH.include?(path)
      end
    end
    self
  end

  def self.require(*groups)
    groups = [:default] if groups.empty?
    groups.each do |group|
      (AUTOREQUIRES[group.to_sym] || []).each do |file, explicit|
        if explicit
          Kernel.require file
        else
          begin
            Kernel.require file
          rescue LoadError
          end
        end
      end
    end
  end

  # Set up load paths unless this file is being loaded after the Bundler gem
  setup unless defined?(Bundler::GEM_LOADED)
end
