development:
  adapter: mongodb
  database: mint-dev
  host: localhost

test:
  adapter: mongodb
  database: mint-test
  host: localhost

production:
  adapter: mongodb
  database: mint-prod
  host: localhost
