defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  # autocreate_indexes: false
  allow_dynamic_fields: false
  # include_root_in_json: false
  # parameterize_keys: true
  raise_not_found_error: true
  reconnect_time: 3
  
development:
  <<: *defaults
  database: mintt_development
  persist_in_safe_mode: true
  
test:
  <<: *defaults
  database: mintt_test
  
# set these environment variables on your prod server
production:
  <<: *defaults
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  database: mint-prod#<%= ENV['MONGOID_DATABASE'] %>
  persist_in_safe_mode: true