defaults: &defaults
  mintt_sender: mintt@epfl.ch
  applications_open: true
  course_dates:
    _2010: - 2010-06-08
           - 2010-06-09
           - 2010-10-06
    _2011: - 2011-06-07
           - 2011-06-08
           - 2011-10-05
    _2012: - 2011-06-05
           - 2011-06-06
           - 2011-10-02

development:
  <<: *defaults
  new_message_recipients: - remy@jilion.com

test:
  <<: *defaults
  new_message_recipients: - remy@jilion.com

production:
  <<: *defaults
  new_message_recipients: - mehdi.aminian@epfl.ch
                          - rosina.amendola@epfl.ch
