defaults: &defaults
  mintt_sender: "Mintt EPFL <mintt.epfl@gmail.com>"
  applications_open: false
  course_dates:
    year_2010:
      - 2010-06-08
      - 2010-06-09
      - 2010-10-06
    year_2011:
      - 2011-06-07
      - 2011-06-08
      - 2011-10-05
    year_2012:
      - 2012-06-05
      - 2012-06-06
      - 2012-10-02
    year_2013:
      day_1:
        - 2013-06-04
        - 2013-06-06
      day_2:
        - 2013-06-05
        - 2013-06-07
      day_3:
        - 2013-10-08
        - 2013-10-09

development:
  <<: *defaults
  new_message_recipients:
    - remy@jilion.com

test:
  <<: *defaults
  new_message_recipients:
    - remy@jilion.com

production:
  <<: *defaults
  new_message_recipients:
    - mehdi.aminian@epfl.ch
    - rosina.amendola@epfl.ch
